# Generated by Django 4.1.4 on 2022-12-29 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Registration Profile',
                'verbose_name_plural': 'Registration Profiles',
                'db_table': 'students_registration_profile',
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('otp', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('logged_in', 'Logged in'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user login',
                'verbose_name_plural': 'user logins',
                'db_table': 'users_user_login',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('', 'Your Gender'), ('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('is_banned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
                'db_table': 'users_profile',
            },
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'logged in user',
                'verbose_name_plural': 'logged in users',
                'db_table': 'users_logged_in_user',
            },
        ),
    ]
