# Generated by Django 4.1.4 on 2022-12-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrationprofile',
            table='registration_profile',
        ),
    ]
