# Generated by Django 4.1.4 on 2022-12-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_registrationprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrationprofile',
            table='users_registration_profile',
        ),
    ]
