# Generated by Django 4.1.4 on 2023-01-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_city_profile_country_profile_pin_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
