# Generated by Django 4.1.4 on 2023-01-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cropping',
        ),
    ]
