# Generated by Django 4.1.4 on 2023-01-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_cropping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='file',
        ),
    ]
