# Generated by Django 4.1.4 on 2023-01-28 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0011_alter_jobitem_amnt_end_per_hrs_and_more'),
        ('users', '0009_rename_photo_profile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppliedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('job', models.ForeignKey(limit_choices_to={'is_deleted': False}, on_delete=django.db.models.deletion.CASCADE, to='web.jobitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user applied job',
                'verbose_name_plural': 'user applied jobs',
                'db_table': 'users_user_applied_job',
            },
        ),
    ]
