# Generated by Django 4.1.4 on 2023-01-28 15:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0011_alter_jobitem_amnt_end_per_hrs_and_more'),
        ('users', '0011_usersavedjob'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersavedjob',
            unique_together={('user', 'job')},
        ),
    ]
