# Generated by Django 4.1.4 on 2023-01-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userappliedjob_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin_created',
            field=models.BooleanField(default=False),
        ),
    ]
