# Generated by Django 4.1.4 on 2023-02-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userappliedjob_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userappliedjob',
            old_name='is_expired',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='usersavedjob',
            old_name='is_expired',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='userappliedjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
