# Generated by Django 4.1.4 on 2023-01-28 05:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='jobs/')),
                ('job_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('skills', models.TextField(blank=True, null=True)),
                ('amnt_per_hrs', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('', 'Job type'), ('freelancer', 'Freelancer'), ('fulltime', 'Fulltime')], max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'web job_item',
                'verbose_name_plural': 'web job_items',
                'db_table': 'webs_job_item',
            },
        ),
    ]
