# Generated by Django 4.1.4 on 2023-01-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='photo',
            field=models.ImageField(upload_to='jobs/'),
        ),
    ]
