# Generated by Django 4.1.4 on 2023-01-28 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_jobitem_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobitem',
            name='state',
        ),
        migrations.AddField(
            model_name='jobitem',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
