# Generated by Django 4.1.4 on 2023-01-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_jobitem_state_jobitem_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobitem',
            old_name='amnt_per_hrs',
            new_name='amnt_end_per_hrs',
        ),
        migrations.AddField(
            model_name='jobitem',
            name='amnt_start_per_hrs',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
