# Generated by Django 4.1.4 on 2023-01-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_amnt_per_hrs_jobitem_amnt_end_per_hrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='industry',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
