# Generated by Django 4.1.4 on 2023-01-28 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_jobitem_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobitem',
            name='experience',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobitem',
            name='job_level',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
