# Generated by Django 4.1.4 on 2023-01-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_jobitem_deadline_jobitem_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='state',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
