# Generated by Django 4.1.4 on 2023-01-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_jobitem_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
