# Generated by Django 4.1.4 on 2023-01-28 14:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_jobitem_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobitem',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='jobitem',
            name='remark',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
