# Generated by Django 4.1.4 on 2023-01-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_description_jobitem_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobitem',
            old_name='remark',
            new_name='description',
        ),
    ]
