# Generated by Django 4.1.4 on 2023-01-28 15:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_rename_remark_jobitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='amnt_end_per_hrs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='amnt_start_per_hrs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
