# Generated by Django 4.1.4 on 2023-02-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_jobitem_amnt_end_per_hrs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobitem',
            name='short_description',
            field=models.TextField(max_length=120),
        ),
    ]
