# Generated by Django 4.1.4 on 2023-02-05 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0012_alter_jobitem_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_job_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
