# Generated by Django 4.1.4 on 2023-02-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_jobitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobitem',
            name='duration',
        ),
    ]
