# Generated by Django 4.1.4 on 2023-02-06 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_profile_facebook_profile_instagram_profile_twitter'),
        ('web', '0014_remove_jobitem_duration'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='jobitem',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_job_profile', to='company.profile'),
        # ),
    ]
