# Generated by Django 4.1.4 on 2023-02-06 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_jobitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobitem',
            name='user',
        ),
    ]
