# Generated by Django 4.1.4 on 2023-02-06 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_profile_facebook_profile_instagram_profile_twitter'),
        ('web', '0016_remove_jobitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='user',
            field=models.ForeignKey(default='9b35190a-9f29-4526-bc1d-bec7c3b0910d', on_delete=django.db.models.deletion.CASCADE, related_name='company_job_profile', to='company.profile'),
            preserve_default=False,
        ),
    ]
