# Generated by Django 4.1.4 on 2023-02-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_jobitem_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobitem',
            options={'verbose_name': 'web job item', 'verbose_name_plural': 'web job items'},
        ),
    ]
