# Generated by Django 4.1.4 on 2023-01-29 09:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('address', models.TextField()),
                ('about', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('is_banned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_admin_created', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company profile',
                'verbose_name_plural': 'company profiles',
                'db_table': 'companies_profile',
            },
        ),
    ]
