# Generated by Django 4.1.4 on 2023-01-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_profile_address_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='company-profile/'),
        ),
    ]
